name: CI Workflow

on: [push, pull_request]

jobs:
  lint-app:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - name: Lint App
        run: echo "Add linting step here"

  build-docker:
    needs: lint-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:v2 ./udagram-api-feed
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:v2

          docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:v2 ./udagram-api-user
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:v2

          docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:v2 ./udagram-frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:v2

          docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-reverseproxy:v2 ./udagram-reverseproxy
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-reverseproxy:v2
